version: '3.5'
services:
  medco-unlynx:
    image: medco/medco-unlynx:dev
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
    - "2000"
    - "2001"
    environment:
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    - CONN_TIMEOUT=10m
    volumes:
    - ./configuration-profile:/medco-configuration
