version: '3.5'
services:
  medco-unlynx:
    image: medco/medco-unlynx:v0.1
    build:
      context: ../
      dockerfile: deployment/Dockerfile
      target: release
    ports:
    - "2000"
    - "2001"
    environment:
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    volumes:
    - ./configuration-profile:/medco-configuration
